import type { SeedJobInput } from '@/types/job';

export const ADMIN_EMAIL = 'chethansaikrishna@gmail.com';

export const FIREBASE_CONFIG = {
  apiKey: 'AIzaSyAS69lrRzb8p2oBtBX8i3Lc25Td_Ks70H0',
  authDomain: 'tensorgo-92cd3.firebaseapp.com',
  projectId: 'tensorgo-92cd3',
  storageBucket: 'tensorgo-92cd3.firebasestorage.app',
  messagingSenderId: '854624673065',
  appId: '1:854624673065:web:4b1fc99d45eb9b1b98ab38',
  measurementId: 'G-10C589363L',
};

export const ROUTES = {
  login: '/(auth)/login',
  signup: '/(auth)/signup',
  emailConfirmation: '/(auth)/email-confirmation',
  completeProfile: '/(onboarding)/complete-profile',
  jobs: '/(app)/(tabs)/jobs',
  applications: '/(app)/(tabs)/applications',
  profile: '/(app)/(tabs)/profile',
  admin: '/(app)/admin',
} as const;

export const DEFAULT_JOBS: SeedJobInput[] = [
  {
    title: 'React Native Developer',
    companyName: 'TensorGo Labs',
    location: 'Bengaluru',
    experienceRequired: '2-4 years',
    description: 'Build mobile features for the job portal using Expo and Firebase.',
    employmentType: 'Full-time',
    salaryRange: '8-12 LPA',
    skills: ['React Native', 'Expo', 'Firebase'],
    slug: 'react-native-developer',
    seedKey: 'job-1',
  },
  {
    title: 'Frontend Engineer',
    companyName: 'BluePeak Systems',
    location: 'Hyderabad',
    experienceRequired: '3-5 years',
    description: 'Own front-end interfaces for internal hiring tools.',
    employmentType: 'Full-time',
    salaryRange: '10-16 LPA',
    skills: ['React', 'TypeScript', 'UI Systems'],
    slug: 'frontend-engineer',
    seedKey: 'job-2',
  },
  {
    title: 'Backend Developer',
    companyName: 'CloudForge',
    location: 'Pune',
    experienceRequired: '2-6 years',
    description: 'Design backend APIs and data flows for recruitment products.',
    employmentType: 'Full-time',
    salaryRange: '9-15 LPA',
    skills: ['Node.js', 'Firestore', 'REST APIs'],
    slug: 'backend-developer',
    seedKey: 'job-3',
  },
  {
    title: 'Full Stack Developer',
    companyName: 'ScaleWorks',
    location: 'Chennai',
    experienceRequired: '4-7 years',
    description: 'Ship full-stack hiring workflows across mobile and admin tools.',
    employmentType: 'Full-time',
    salaryRange: '12-18 LPA',
    skills: ['React', 'Node.js', 'Firebase'],
    slug: 'full-stack-developer',
    seedKey: 'job-4',
  },
  {
    title: 'QA Automation Engineer',
    companyName: 'QualiTrack',
    location: 'Remote',
    experienceRequired: '2-4 years',
    description: 'Automate QA for job application and admin flows.',
    employmentType: 'Full-time',
    salaryRange: '7-11 LPA',
    skills: ['Playwright', 'Appium', 'CI/CD'],
    slug: 'qa-automation-engineer',
    seedKey: 'job-5',
  },
  {
    title: 'UI/UX Designer',
    companyName: 'NorthArc Studio',
    location: 'Mumbai',
    experienceRequired: '3-6 years',
    description: 'Design high-conversion job browsing and profile completion flows.',
    employmentType: 'Full-time',
    salaryRange: '9-13 LPA',
    skills: ['Figma', 'Design Systems', 'Prototyping'],
    slug: 'ui-ux-designer',
    seedKey: 'job-6',
  },
  {
    title: 'DevOps Engineer',
    companyName: 'InfraNest',
    location: 'Noida',
    experienceRequired: '4-8 years',
    description: 'Improve deployment automation and reliability pipelines.',
    employmentType: 'Full-time',
    salaryRange: '14-20 LPA',
    skills: ['Docker', 'GCP', 'Monitoring'],
    slug: 'devops-engineer',
    seedKey: 'job-7',
  },
  {
    title: 'Data Analyst',
    companyName: 'InsightGrid',
    location: 'Gurugram',
    experienceRequired: '1-3 years',
    description: 'Analyze hiring funnel performance and application trends.',
    employmentType: 'Full-time',
    salaryRange: '6-10 LPA',
    skills: ['SQL', 'Analytics', 'Dashboards'],
    slug: 'data-analyst',
    seedKey: 'job-8',
  },
  {
    title: 'Product Manager',
    companyName: 'TalentFlow',
    location: 'Bengaluru',
    experienceRequired: '5-8 years',
    description: 'Lead roadmap decisions for recruiting and applicant workflows.',
    employmentType: 'Full-time',
    salaryRange: '18-25 LPA',
    skills: ['Product Strategy', 'Agile', 'User Research'],
    slug: 'product-manager',
    seedKey: 'job-9',
  },
  {
    title: 'Support Specialist',
    companyName: 'HireAssist',
    location: 'Remote',
    experienceRequired: '1-2 years',
    description: 'Handle candidate support requests and operational workflows.',
    employmentType: 'Full-time',
    salaryRange: '4-6 LPA',
    skills: ['Customer Support', 'Communication', 'CRM'],
    slug: 'support-specialist',
    seedKey: 'job-10',
  },
];

export const VALIDATION = {
  passwordMinLength: 6,
  phoneMinLength: 10,
  yearsOfExperienceMin: 0,
  yearsOfExperienceMax: 50,
};